### PR TITLE
Update Post Style

### PR DESCRIPTION
**Pull request by ADurante**
@silvanogai, comments in the code.

### CODE REVIEW

**Comment by silvanogai** [comment]
Frontmatter uses YALM syntax, HTML comments are considered errors. Need to use YALM comments.

**published: false** suppresses page rendering. It can be bypassed by jekyll serve --unpublished,
but I have not found a way to access an unrendered page through a URL on jekyll.

You can still access it on github.com, but it is not rendered the same way

**Comment by ADurante** [comment]
Hi Silvano, you are right! I had considered it as a Markdown file!

**Comment by ADurante** [comment]
@silvanogai if I comment in YAML with a hashtag, it reads it to me as first-level header (H1)...

**Comment by silvanogai** [comment]
Closing this pull request. Implemented solution described in:
https://gist.github.com/carlo/2870636

Modified files feed.xml and _layouts/home.html

**Pull request closed without merging**
